create table temp1
(
    id int primary key,
    data varchar2(34)
);

insert into temp1 values(1,'some data');
insert into temp1 values(2,'some data');
insert into temp1 values(3,'some data');
insert into temp1 values(4,'some data');

select * from temp1;

delete from temp1 where id=4;

DROP TABLE temp1;
 

create table temp2(
id int GENERATED BY DEFAULT AS IDENTITY START WITH 10 PRIMARY KEY,
data varchar2(34)
);
 
CREATE TABLE date_tab 
(
   ts_col      TIMESTAMP,
   tsltz_col   TIMESTAMP WITH LOCAL TIME ZONE,
   tstz_col    TIMESTAMP WITH TIME ZONE
);

ALTER SESSION SET TIME_ZONE = '-8:00';
INSERT INTO date_tab VALUES (  
   TIMESTAMP'1999-12-01 10:00:00',
   TIMESTAMP'1999-12-01 10:00:00',
   TIMESTAMP'1999-12-01 10:00:00');
INSERT INTO date_tab VALUES (
   TIMESTAMP'1999-12-02 10:00:00 -8:00', 
   TIMESTAMP'1999-12-02 10:00:00 -8:00',
   TIMESTAMP'1999-12-02 10:00:00 -8:00');
   
ALTER SESSION SET TIME_ZONE = '+5:30';
INSERT INTO date_tab VALUES (  
   TIMESTAMP'1999-12-01 10:00:00',
   TIMESTAMP'1999-12-01 10:00:00',
   TIMESTAMP'1999-12-01 10:00:00');
INSERT INTO date_tab VALUES (
   TIMESTAMP'1999-12-02 10:00:00 +5:30', 
   TIMESTAMP'1999-12-02 10:00:00 +5:30',
   TIMESTAMP'1999-12-02 10:00:00 +5:30');
   
   
SELECT TO_CHAR(ts_col, 'DD-MON-YYYY HH24:MI:SSxFF'),
TO_CHAR(tstz_col, 'DD-MON-YYYY HH24:MI:SSxFF TZH:TZM')
FROM date_tab;

SELECT SESSIONTIMEZONE,    TO_CHAR(tsltz_col, 'DD-MON-YYYY HH24:MI:SSxFF')
FROM date_tab;

SELECT TO_CHAR('01110' + 1) FROM dual;   

SELECT TO_CHAR(-10000,'L99G999D99MI') "Amount" FROM DUAL;

SELECT 
    empno,ename,deptno,
    DECODE(deptno,
            10,	'ACCOUNTING',
            40,	'OPERATIONS',
            20,	'RESEARCH',
            30,	'SALES',
            'No Specific Department')
    FROM 
        emp;


SELECT 
    empno,ename,sal,comm,
    CASE
        WHEN comm=0 then 500
        WHEN comm is null then 0
        WHEN comm>0 and comm<500 then comm+500
        ELSE comm
    END as updated_comm
FROM 
    emp
WHERE 
    ename!='KING'
ORDER BY
    comm;
    
SELECT SAL FROM EMP ORDER BY SAL;

SELECT 
    RANK(5000) WITHIN GROUP (ORDER BY SAL)AS "RANK Asc",
    RANK(5000) WITHIN GROUP (ORDER BY SAL DESC)AS "RANK desc"
    FROM EMP; 
 
SELECT deptno,sal, RANK() OVER (PARTITION BY deptno ORDER BY sal) as "RankPER DEPT" FROM emp;


SELECT deptno,sal,
RANK()OVER ( ORDER BY sal) as "Rank PER SAL "
FROM emp
ORDER BY SAL;


SELECT * FROM EMP
        WHERE 
            DEPTNO IN (SELECT DEPTNO FROM DEPT 
                            WHERE BRANCHNO IN (SELECT BRANCHNO FROM BRANCH WHERE LOCATION='NEW YORK'))

select * from branch;                            
                            
select * from emp where deptno in (select deptno from dept where branchno in (select branchno from branch where location='new yourk'));

